// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu_wsHnGsDgfa6UkgbMadw9iHAVObqtO4',
    appId: '1:341120970628:web:b24cd721a8ccfa5bf7b7d1',
    messagingSenderId: '341120970628',
    projectId: 'contact-form-d1b3d',
    authDomain: 'contact-form-d1b3d.firebaseapp.com',
    databaseURL: 'https://contact-form-d1b3d-default-rtdb.firebaseio.com',
    storageBucket: 'contact-form-d1b3d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcjbNzyovPfnUQ0FuKXVcPffyL7-byOVk',
    appId: '1:341120970628:android:18e6303e37e4f5f1f7b7d1',
    messagingSenderId: '341120970628',
    projectId: 'contact-form-d1b3d',
    databaseURL: 'https://contact-form-d1b3d-default-rtdb.firebaseio.com',
    storageBucket: 'contact-form-d1b3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc9sUTeRRrDpRwWWZZv1kwahU4XTzNUvo',
    appId: '1:341120970628:ios:3789cf7c8c957da7f7b7d1',
    messagingSenderId: '341120970628',
    projectId: 'contact-form-d1b3d',
    databaseURL: 'https://contact-form-d1b3d-default-rtdb.firebaseio.com',
    storageBucket: 'contact-form-d1b3d.firebasestorage.app',
    iosBundleId: 'com.example.collegeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc9sUTeRRrDpRwWWZZv1kwahU4XTzNUvo',
    appId: '1:341120970628:ios:3789cf7c8c957da7f7b7d1',
    messagingSenderId: '341120970628',
    projectId: 'contact-form-d1b3d',
    databaseURL: 'https://contact-form-d1b3d-default-rtdb.firebaseio.com',
    storageBucket: 'contact-form-d1b3d.firebasestorage.app',
    iosBundleId: 'com.example.collegeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu_wsHnGsDgfa6UkgbMadw9iHAVObqtO4',
    appId: '1:341120970628:web:eb9ab89480a02079f7b7d1',
    messagingSenderId: '341120970628',
    projectId: 'contact-form-d1b3d',
    authDomain: 'contact-form-d1b3d.firebaseapp.com',
    databaseURL: 'https://contact-form-d1b3d-default-rtdb.firebaseio.com',
    storageBucket: 'contact-form-d1b3d.firebasestorage.app',
  );

}